CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR(255)                                        NOT NULL,
    email VARCHAR(255)                                        NOT NULL,
    CONSTRAINT unique_email UNIQUE (email)
);

CREATE TABLE items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(1000),
    available   BOOLEAN DEFAULT TRUE,
    user_id     BIGINT                                              NOT NULL,
    CONSTRAINT fk_items_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_id BIGINT NOT NULL,
    item_id BIGINT                                              NOT NULL,
    status  VARCHAR(50),
    CONSTRAINT fk_booking_items FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS booking_days
(
    item_id BIGINT NOT NULL REFERENCES items(id),
    date_of_booking DATE NOT NULL,
    CONSTRAINT composite_pk_booking_days PRIMARY KEY (item_id, date_of_booking)
);